### ISSUE TITLE
Unable to respond to null to non-null state changes and vice versa

### ISSUE THREAD

**Issue by craigomac** [leocavalcante/Flutter-ReduRx#4]
On this line it seems that a builder won't be invoked if the sub-state we're monitoring from a widget is `null`:

https://github.com/leocavalcante/Flutter-ReduRx/blob/f693c4044c7ba9d625fbfa480650c279975316c6/lib/flutter_redurx.dart#L72

Here's my use case:

* I have a widget representing some object in a list of objects
* When the user touches down, I change a field `highlightedObject` in the app state via `Action` dispatch to match the object represented by the item
* I then want my widget to rebuild with a different visual style if the object it represents matches the `highlightedObject` in the app state, so I've wrapped it in a `Connector` that `convert`s using the state's `highlightedObject`

And what happens:

* The initial `highlightedObject` is `null`, so the `Connector` for my object widget doesn't call the `builder` I provided — so no widgets in my list are shown

Is this by design? Thanks!

**Comment by leocavalcante** [comment]
Yes, this is by design to enforce a default value, even something like a [NullObject](https://en.wikipedia.org/wiki/Null_object_pattern) and avoid things like [NullPointerExceptions](https://en.wikibooks.org/wiki/Java_Programming/Preventing_NullPointerException).

Please, try `v0.4.3`, I added a `nullable` attribute to `Connect` so it can by-pass the  `null` `snapshot.data` validation. You can see it in action at this test: https://github.com/leocavalcante/Flutter-ReduRx/blob/master/test/flutter_redurx_test.dart#L120

However, I really encourage you to design a default value for `highlightedObject` that is meaningful for your domain and won't break things unexpectedly on runtime like `null` usually does.

Cheers!

**Comment by craigomac** [comment]
This morning when I woke up one of my first thoughts was that I should have used `convert` to produce a view of the state that was a `bool` and represented "is the highlighted object equal to the object represented by this widget". Then it would always be `true` or `false`. Funny how that happens 😁.

Thanks for your good points. Thanks for the `nullable` attribute!
